import categoryMen from '../../assets/images/nova-category-men.jpg'
import categoryWomen from '../../assets/images/nova-category-women.jpg'
import categoryAccessories from '../../assets/images/nova-category-accessories.jpg'
import homeHero from '../../assets/images/nova-home-hero.jpg'
import productSneakers from '../../assets/images/nova-product-sneakers.jpg'
import productBag from '../../assets/images/nova-product-bag.jpg'
import productSweater from '../../assets/images/nova-product-sweater.jpg'
import productWatch from '../../assets/images/nova-product-watch.jpg'

const filters = {
  newArrivals: [
    { label: 'Tout', value: 'all' },
    { label: 'Homme', value: 'Homme' },
    { label: 'Femme', value: 'Femme' },
    { label: 'Accessoires', value: 'Accessoires' },
  ],
  apparel: [
    { label: 'Tout', value: 'all' },
    { label: 'Vêtements', value: 'Vêtements' },
    { label: 'Chaussures', value: 'Chaussures' },
    { label: 'Accessoires', value: 'Accessoires' },
  ],
  accessories: [
    { label: 'Tout', value: 'all' },
    { label: 'Sacs', value: 'Sacs' },
    { label: 'Montres', value: 'Montres' },
    { label: 'Bijoux', value: 'Bijoux' },
    { label: 'Lunettes', value: 'Lunettes' },
  ],
}

const apparelSizes = ['XS', 'S', 'M', 'L', 'XL']
const shoeSizes = ['39', '40', '41', '42', '43']
const accessorySizes = ['Unique']

const neutralColors = [
  { name: 'Noir', value: '#111111' },
  { name: 'Beige', value: '#d8cdbd' },
  { name: 'Kaki', value: '#6f725c' },
  { name: 'Gris', value: '#8b8b88' },
]

const accessoryColors = [
  { name: 'Noir', value: '#111111' },
  { name: 'Brun', value: '#7b4f34' },
  { name: 'Doré', value: '#c6a557' },
]

const baseProducts = [
  {
    id: 'chemise-lin',
    department: 'Homme',
    group: 'Vêtements',
    name: 'Chemise en lin',
    description: 'Lin léger',
    image: categoryMen,
    imageAlt: 'Homme portant une chemise en lin',
    imagePosition: '42% center',
    rating: 5,
    reviews: 88,
    price: '490 DH',
    priceValue: 490,
    isNew: true,
    sortIndex: 1,
  },
  {
    id: 'blazer-essentiel',
    department: 'Femme',
    group: 'Vêtements',
    name: 'Blazer essentiel',
    description: 'Coupe structurée',
    image: categoryWomen,
    imageAlt: 'Femme portant un blazer clair',
    imagePosition: '48% center',
    rating: 5,
    reviews: 96,
    price: '890 DH',
    priceValue: 890,
    isNew: true,
    sortIndex: 2,
  },
  {
    id: 'sac-elise',
    department: 'Accessoires',
    group: 'Sacs',
    name: 'Sac Élise',
    description: 'Sac noir structuré',
    image: productBag,
    imageAlt: 'Sac Élise noir avec fermoir doré',
    rating: 5,
    reviews: 89,
    price: '1 290 DH',
    priceValue: 1290,
    isNew: true,
    sortIndex: 3,
  },
  {
    id: 'baskets-nova',
    department: 'Homme',
    group: 'Chaussures',
    name: 'Baskets Nova',
    description: 'Baskets blanches',
    image: productSneakers,
    imageAlt: 'Baskets blanches Nova',
    rating: 5,
    reviews: 124,
    price: '680 DH',
    priceValue: 680,
    isNew: true,
    sortIndex: 4,
  },
  {
    id: 'pull-cachemire',
    department: 'Homme',
    group: 'Vêtements',
    name: 'Pull en cachemire',
    description: 'Maille olive zippée',
    image: productSweater,
    imageAlt: 'Pull en cachemire vert olive',
    rating: 5,
    reviews: 102,
    price: '850 DH',
    oldPrice: '1 090 DH',
    discount: '-22%',
    priceValue: 850,
    isNew: true,
    unavailableSizes: ['XS'],
    sortIndex: 5,
  },
  {
    id: 'robe-fluide',
    department: 'Femme',
    group: 'Vêtements',
    name: 'Robe fluide',
    description: 'Robe claire fluide',
    image: categoryWomen,
    imageAlt: 'Robe fluide dans une teinte claire',
    imagePosition: '50% center',
    rating: 5,
    reviews: 79,
    price: '790 DH',
    priceValue: 790,
    isNew: true,
    sortIndex: 6,
  },
  {
    id: 'montre-horizon',
    department: 'Accessoires',
    group: 'Montres',
    name: 'Montre Horizon',
    description: 'Montre à cadran vert',
    image: productWatch,
    imageAlt: 'Montre Horizon avec cadran vert et bracelet brun',
    rating: 5,
    reviews: 76,
    price: '1 490 DH',
    priceValue: 1490,
    isNew: true,
    sortIndex: 7,
  },
  {
    id: 'lunettes-signature',
    department: 'Accessoires',
    group: 'Lunettes',
    name: 'Lunettes signature',
    description: 'Lunettes solaires foncées',
    image: categoryAccessories,
    imageAlt: 'Lunettes signature sur pierre claire',
    imagePosition: '12% center',
    rating: 5,
    reviews: 71,
    price: '390 DH',
    priceValue: 390,
    isNew: true,
    sortIndex: 8,
  },
  {
    id: 'veste-essentielle',
    department: 'Homme',
    group: 'Vêtements',
    name: 'Veste essentielle',
    description: 'Veste noire moderne',
    image: homeHero,
    imageAlt: 'Homme portant une veste essentielle',
    imagePosition: '70% center',
    rating: 5,
    reviews: 84,
    price: '890 DH',
    priceValue: 890,
    isNew: true,
    sortIndex: 9,
  },
  {
    id: 'pantalon-chino',
    department: 'Homme',
    group: 'Vêtements',
    name: 'Pantalon chino',
    description: 'Pantalon clair',
    image: categoryMen,
    imageAlt: 'Pantalon chino dans une teinte claire',
    imagePosition: '58% center',
    rating: 4,
    reviews: 56,
    price: '590 DH',
    priceValue: 590,
    isNew: false,
    sortIndex: 10,
  },
  {
    id: 'polo-maille',
    department: 'Homme',
    group: 'Vêtements',
    name: 'Polo en maille',
    description: 'Polo texturé',
    image: categoryMen,
    imageAlt: 'Polo en maille pour homme',
    imagePosition: '52% center',
    rating: 5,
    reviews: 68,
    price: '450 DH',
    priceValue: 450,
    isNew: true,
    sortIndex: 11,
  },
  {
    id: 'chemisier-satin',
    department: 'Femme',
    group: 'Vêtements',
    name: 'Chemisier en satin',
    description: 'Chemisier lumineux',
    image: categoryWomen,
    imageAlt: 'Chemisier en satin clair',
    imagePosition: '42% center',
    rating: 5,
    reviews: 72,
    price: '490 DH',
    priceValue: 490,
    isNew: true,
    sortIndex: 12,
  },
  {
    id: 'pantalon-palazzo',
    department: 'Femme',
    group: 'Vêtements',
    name: 'Pantalon palazzo',
    description: 'Pantalon fluide',
    image: categoryWomen,
    imageAlt: 'Pantalon palazzo clair',
    imagePosition: '58% center',
    rating: 4,
    reviews: 59,
    price: '590 DH',
    priceValue: 590,
    isNew: false,
    sortIndex: 13,
  },
  {
    id: 'sandales-elegantes',
    department: 'Femme',
    group: 'Chaussures',
    name: 'Sandales élégantes',
    description: 'Sandales en cuir',
    image: productSneakers,
    imageAlt: 'Sandales élégantes',
    rating: 5,
    reviews: 64,
    price: '550 DH',
    priceValue: 550,
    isNew: false,
    sortIndex: 14,
  },
  {
    id: 'ceinture-cuir',
    department: 'Accessoires',
    group: 'Sacs',
    name: 'Ceinture en cuir',
    description: 'Ceinture brune',
    image: categoryAccessories,
    imageAlt: 'Ceinture en cuir brun',
    imagePosition: '82% center',
    rating: 4,
    reviews: 41,
    price: '350 DH',
    priceValue: 350,
    isNew: true,
    sortIndex: 15,
  },
  {
    id: 'collier-dore',
    department: 'Accessoires',
    group: 'Bijoux',
    name: 'Collier doré',
    description: 'Collier fin doré',
    image: categoryAccessories,
    imageAlt: 'Collier doré',
    imagePosition: '40% center',
    rating: 5,
    reviews: 58,
    price: '290 DH',
    priceValue: 290,
    isNew: true,
    sortIndex: 16,
  },
  {
    id: 'foulard-soie',
    department: 'Accessoires',
    group: 'Sacs',
    name: 'Foulard en soie',
    description: 'Foulard satiné',
    image: categoryAccessories,
    imageAlt: 'Foulard en soie',
    imagePosition: '74% center',
    rating: 4,
    reviews: 38,
    price: '450 DH',
    priceValue: 450,
    isNew: true,
    sortIndex: 17,
  },
  {
    id: 'portefeuille-classique',
    department: 'Accessoires',
    group: 'Sacs',
    name: 'Portefeuille classique',
    description: 'Portefeuille brun',
    image: categoryAccessories,
    imageAlt: 'Portefeuille classique en cuir brun',
    imagePosition: '64% center',
    rating: 4,
    reviews: 44,
    price: '390 DH',
    priceValue: 390,
    isNew: true,
    sortIndex: 18,
  },
  {
    id: 'bracelet-essentiel',
    department: 'Accessoires',
    group: 'Bijoux',
    name: 'Bracelet essentiel',
    description: 'Bracelet doré minimal',
    image: categoryAccessories,
    imageAlt: 'Bracelet essentiel doré',
    imagePosition: '45% center',
    rating: 5,
    reviews: 52,
    price: '250 DH',
    priceValue: 250,
    isNew: true,
    sortIndex: 19,
  },
]

const products = baseProducts.map((product) => ({
  ...product,
  availability: product.availability || 'En stock',
  sizes:
    product.sizes ||
    (product.group === 'Chaussures'
      ? shoeSizes
      : product.department === 'Accessoires'
        ? accessorySizes
        : apparelSizes),
  colors: product.colors || (product.department === 'Accessoires' ? accessoryColors : neutralColors),
  unavailableSizes: product.unavailableSizes || [],
}))

const getProducts = (ids) =>
  ids.map((id, index) => ({
    ...products.find((product) => product.id === id),
    sortIndex: index + 1,
  }))

export const catalogPages = {
  newArrivals: {
    pageKey: 'nouveautes',
    title: 'Nouveautés',
    breadcrumb: ['Accueil', 'Nouveautés'],
    description: 'Découvrez les dernières pièces de notre collection.',
    heroImage: homeHero,
    heroImageAlt: 'Nouvelle collection NOVA portée par un couple',
    products: getProducts([
      'chemise-lin',
      'blazer-essentiel',
      'sac-elise',
      'baskets-nova',
      'pull-cachemire',
      'robe-fluide',
      'montre-horizon',
      'lunettes-signature',
    ]),
    categoryField: 'department',
    filterOptions: filters.newArrivals,
  },
  men: {
    pageKey: 'homme',
    title: 'Homme',
    breadcrumb: ['Accueil', 'Homme'],
    description: 'Des essentiels intemporels pour une allure moderne.',
    heroImage: homeHero,
    heroImageAlt: 'Homme portant une veste noire NOVA',
    products: getProducts([
      'chemise-lin',
      'veste-essentielle',
      'pantalon-chino',
      'baskets-nova',
      'pull-cachemire',
      'polo-maille',
      'montre-horizon',
      'lunettes-signature',
    ]),
    categoryField: 'group',
    filterOptions: filters.apparel,
  },
  women: {
    pageKey: 'femme',
    title: 'Femme',
    breadcrumb: ['Accueil', 'Femme'],
    description: 'Des pièces élégantes pour révéler votre style.',
    heroImage: categoryWomen,
    heroImageAlt: 'Femme portant une veste claire NOVA',
    products: getProducts([
      'robe-fluide',
      'blazer-essentiel',
      'sac-elise',
      'baskets-nova',
      'chemisier-satin',
      'pantalon-palazzo',
      'sandales-elegantes',
      'lunettes-signature',
    ]),
    categoryField: 'group',
    filterOptions: filters.apparel,
  },
  accessories: {
    pageKey: 'accessoires',
    title: 'Accessoires',
    breadcrumb: ['Accueil', 'Accessoires'],
    description: 'Les détails qui font toute la différence.',
    heroImage: categoryAccessories,
    heroImageAlt: 'Sac, montre, lunettes et foulard NOVA',
    products: getProducts([
      'sac-elise',
      'montre-horizon',
      'lunettes-signature',
      'ceinture-cuir',
      'collier-dore',
      'foulard-soie',
      'portefeuille-classique',
      'bracelet-essentiel',
    ]),
    categoryField: 'group',
    filterOptions: filters.accessories,
  },
}
export { products }
